plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/davidmarsh/Desktop/LiFi NYC/_Utilities/Websites/output/little-fight-pill-demo"
publishOrigin = "default"
base = "/Users/davidmarsh/Desktop/LiFi NYC/_Utilities/Websites/output/little-fight-pill-demo"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]